<!DOCTYPE html>
<html lang="en">
<?php include("public/layout/_head.php"); ?>

<body class="p-4">
    <h4 class="fw-bold text-center">Lamda Book Store</h4>
    <span class="text-center d-block px-4">Perumahan Griya Shanta Permata, N-524, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141</span>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID Buku</th>
                    <th>Nama Buku</th>
                    <th>Jumlah</th>
                    <th>Diskon</th>
                    <th>Harga</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($dataBuku as $buku) : ?>
                    <tr>
                        <td><?= $buku->id ?></td>
                        <td><?= $buku->nama_buku ?></td>
                        <td><?= $buku->jumlah ?></td>
                        <td><?= $buku->disc ?></td>
                        <td><?= rupiah($buku->harga) ?></td>
                        <td><?= rupiah($buku->total) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h5>Total Harga : <span class="text-danger fw-bold"><?= rupiah($totalHarga) ?></span></h5>
        </div>
        <div class="col-md-6 text-end">
            <h5>Total Bayar : <span class="text-danger fw-bold"><?= rupiah($uangBayar); ?></span></h5>
        </div>
        <div class="text-end">
            <h5>Kembalian : <span class="fw-bold"><?= rupiah($uangKembali) ?></span></h5>
        </div>
    </div>
    <span>Transaksi dilakukan pada : <span class="fw-bold"><?= $tglTransaksi; ?></span></span>

    <?php include("public/layout/_script.php") ?>
    <script src="js/print.js"></script>
</body>

</html>